<?php

namespace app\controllers;

use app\helpers\TasksHelper;
use app\models\Chain;
use app\models\ChainClonesSteps;
use app\models\ChangeTask;
use app\models\FileLoad;
use app\models\Files;
use app\models\FilesTaskSteps;
use app\models\Groups;
use app\models\StepFiles;
use app\models\Steps;
use app\models\TaskEdit;
use app\models\TaskTable;
use app\models\User;
use app\services\TaskService;
use app\services\TaskStatusService;
use Codeception\Step\Comment;
use Yii;
use yii\data\ActiveDataProvider;
use app\models\Task;
use app\models\TaskSearch;
use yii\db\ActiveQuery;
use yii\db\Query;
use app\models\SelectUserStep;
use yii\debug\models\timeline\DataProvider;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\ChainClones;
use app\models\StepClonesComment;
use yii\web\UploadedFile;
use app\models\ExternalSource;
use yii\helpers\Json;


class TaskController extends \yii\web\Controller
{
    private $taskService;
    private $taskStatusService;

    public function __construct(
        $id,
        $module,
        TaskService $taskService,
        TaskStatusService $taskStatusService,
        array $config = [])
    {
        $this->taskService = $taskService;
        $this->taskStatusService = $taskStatusService;
        parent::__construct($id, $module, $config);
    }

    public function behaviors()
    {
       return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {

        return $this->render('index');
    }

    public function actionList($id_project)
    {
        $taskSearch = new TaskSearch();
        $dataProvider = $taskSearch->search(\Yii::$app->request->get());
        $dataProvider->setPagination([

        ]);
        $dataProvider->query->andFilterWhere(['id_project' => $id_project]);
        // $dataProvider->query->where('id_project=' . $id_project);
        /* $dataProvider = new ActiveDataProvider([
             'query' => Task::find()->where(['id_project' => $id_project]),
             'pagination'    => [
                 'pageSize'  => $page_size
             ]
         ]);*/
        return $this->render('list', [
            'dataProvider' => $dataProvider,
            'taskSearch' => $taskSearch
        ]);
    }


    /**
     * Получаем задачи по статусу
     *
     * @param string $status
     * @param int $page_size
     * @return string
     */
    public function actionListStatus($status = 'all', $id_project = null)
    {
        $taskSearch = new TaskSearch();
        $dataProvider = $taskSearch->search(\Yii::$app->request->get());

        if($status != 'all'){
            $dataProvider->query->andFilterWhere(['status' => $status]);
        }
        $dataProvider->query->andFilterWhere(['id_project' => $id_project]);
        return $this->render('list', [
            'dataProvider' => $dataProvider,
            'taskSearch' => $taskSearch
        ]);
    }


    public function actionListStatusUser($status, $id_user)
    {
        $ids = Task::getTaskByWorker($id_user, true);
        $taskSearch = new TaskSearch();//
        $dataProvider = $taskSearch->search(\Yii::$app->request->get());
        $dataProvider->setPagination([

        ]);

        if($status != 'all'){
            $dataProvider->query->andFilterWhere(['status' => $status]);
        }
        $dataProvider->query->andFilterWhere(['in', Task::tableName().'.id', $ids]);
        return $this->render('list', [
            'dataProvider' => $dataProvider,
            'taskSearch' => $taskSearch
        ]);
    }

    public function actionListStatusDate($status, $from, $to, $page_size = 10)
    {
        $taskSearch = new TaskSearch();
        $dataProvider = $taskSearch->search(\Yii::$app->request->get());
        $dataProvider->setPagination([
            'pageSize' => $page_size
        ]);
        if($status != 'all'){
            $dataProvider->query->andFilterWhere(['status' => $status]);
        }
        if($from){
            $dataProvider->query->andFilterWhere(['>=', 'deadline', $from]);
        }
        if($to){
            $dataProvider->query->andFilterWhere(['<=', 'deadline', $to]);
        }
        return $this->render('list', [
            'dataProvider' => $dataProvider,
            'taskSearch' => $taskSearch
        ]);
    }

    public function actionUpdate($id)
    {
        $task = Task::findOne($id);

        $modelEdit = new TaskEdit();
        if (!empty(Yii::$app->request->post())) {
            $post = Yii::$app->request->post();
            $task->load(Yii::$app->request->post());
            $task->created = date('Y-m-d H:i:s', strtotime($task->created));
            $task->deadline = date('Y-m-d H:i:s', strtotime($post['Task']['deadline']));
            ChainClones::deleteByTaskId($id);
            $modelEdit->load($post);
            $clone = new ChainClones();
            $clone->id_task = $id;
            $clone->id_chain = $modelEdit->id_chain;
            $clone->save();
            foreach ($post['SelectUserStep'] as $i => $step) {
                $post['SelectUserStep'][$i]['status'] = $post['ChainClonesSteps'][$i]['status'];
            }
            $is_rework = false;
            foreach ($post['SelectUserStep'] as $item) {
                $clone_step = new ChainClonesSteps();
                $clone_step->id_clone = $clone->id;
                $clone_step->id_step = $item['id_step'];
                $clone_step->id_user = $item['id_user'];
                $clone_step->status = $item['status'];
                if ($item['status'] == 2) {
                    $is_rework = true;
                }
                $clone_step->save();
            }
            if ($is_rework) {
                $task->status = 2;
            }
            $task->save();
            $this->redirect('/task/list?id_project=' . $task->id_project);
        }
        return $this->render('update', [
            'task' => $task,
            'modelEdit' => $modelEdit
        ]);
    }


    /**
     * Ajax загрузка цепочки этапов;
     *
     * @param null $q
     * @param null $id
     * @return array
     */
    public function actionChainList($q = null, $id = null)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        $query = new Query();
        if (!is_null($q)) {
            $query->select('id, name as text')
                ->from('chain')
                ->where(['like', 'name', $q])
                ->limit(20);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        } else if ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => Chain::find($id)->name];
        } else {
            $query->select('id, name as text')
                ->from('chain');
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        }
        return $out;
    }

    public function actionAddFields($id)
    {
        $form = new ActiveForm();
        $chain = Chain::findOne($id);
        $modelSteps = [];
        foreach ($chain->getSteps()->orderBy(['sort' => SORT_ASC])->all() as $step) {
            $modelSteps[] = new SelectUserStep([
                'id_step' => $step->id,
                'label' => $step->name,
                'id_group' => $step->id_group
            ]);
        }
        return $this->renderAjax('add-fields', [
            'form' => $form,
            'chain' => $chain,
            'modelSteps' => $modelSteps
        ]);

    }

    /**
     * Вывосдим список для редакрования статуса задачи;
     *
     * @param $id_chain
     */
    public function actionStepList($id_chain)
    {
        $form = new ActiveForm();
        $chain = Chain::findOne($id_chain);
        $modelsClonesSteps = [];
        foreach ($chain->getSteps()->orderBy(['sort' => SORT_ASC])->all() as $step) {
            $modelsClonesSteps[] = new ChainClonesSteps([
                'id_step' => $step->id,
                'status' => 0,
            ]);
        }

        return $this->renderAjax('step-list', [
            'modelsClonesSteps' => $modelsClonesSteps,
            'form' => $form
        ]);
    }

    public function actionUsersList($id_group, $q = null)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $groups = Groups::findOne($id_group);
        if (!is_null($q)) {
            $users = $groups->getUsers()->where(['like', 'surname', $q])
                ->orWhere(['like', 'name', $q])
                ->asArray()->all();
        } else {
            $users = $groups->getUsers()->asArray()->all();
        }

        $add_users = User::find()->where(['is_outer' => 1])->one();
        $users[] = $add_users;
        $results = [];
        foreach ($users as $user) {
            if ($user->is_outer == 1) {
                $results[] = [
                    'id' => $user['id'],
                    'text' => '<strong style="color:red">Внешний сотрудник!</strong>'
                ];
            } else {
                $results[] = [
                    'id' => $user['id'],
                    'text' => $user['surname'] . ' ' . $user['name'] . ' (' . $user['email'] . ')'
                ];
            }

        }
        $out['results'] = $results;
        return $out;
    }

    public function actionCard($id)
    {
        $task = Task::findOne($id);

        return $this->render('card', [
            'task' => $task
        ]);
    }


    public function actionRework($id_clone, $id_task)
    {
        $step = ChainClonesSteps::findOne($id_clone);
        $task = Task::findOne($id_task);
        $this->taskStatusService->setStatusRework($step, $task);
        $step->resetStatuses();
        $step->changeStatus(ChainClonesSteps::STATUS_REWORK);
        $this->redirect(['task/card', 'id' => $id_task]);
    }

    public function actionDone($id_clone, $id_task)
    {
        $task = Task::findOne($id_task);
        $step = ChainClonesSteps::findOne($id_clone);
        $this->taskStatusService->setStatusDone($step, $task);
        $this->taskService->setWorkStatus($task);
        $this->redirect(['task/card', 'id' => $id_task]);
    }

    public function actionWorking($id_clone, $id_task)
    {
        $task = Task::findOne($id_task);
        $step = ChainClonesSteps::find()
            ->with('step')
             ->where(['id' => $id_clone])
             ->limit(1)
            ->one();
        $this->taskStatusService->setStatusWork($step, $task);
       // $step->changeStatus(ChainClonesSteps::STATUS_WORK);
        $this->taskService->setWorkStatus($task);

        $this->redirect(['task/card', 'id' => $id_task]);
    }

    public function actionComment($id_clone)
    {
        $model = new StepClonesComment();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            $model->save();
            $step = ChainClonesSteps::findOne($id_clone);
            $step->changeStatus(ChainClonesSteps::STATUS_REWORK);
            $step->resetStatuses();
            $task = $step->clone->task;
            $this->taskStatusService->setStatusRework($step, $task);
            return true;
        }
        return $this->renderAjax('comment', [
            'model' => $model,
            'id_clone' => $id_clone
        ]);
    }

    public function actionUpload($id_task, $id_step)
    {
        $model = Steps::findOne($id_step);
        $file = new FileLoad();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            $file->file = UploadedFile::getInstances($file, 'file');
            foreach ($file->file as $item) {
                $modelFile = new Files();
                $modelFile['real-name'] = $item->baseName;
                $modelFile->name = uniqid();
                $modelFile->tmp = $modelFile->name . '.' . $item->extension;
                $item->saveAs(Yii::getAlias('@web') . 'uploads/files/' . $modelFile->tmp);
                $modelFile->save();
                $files_steps = new FilesTaskSteps();
                $files_steps->id_step = $id_step;
                $files_steps->id_task = $id_task;
                $files_steps->id_file = $modelFile->id;
                $files_steps->save();
            }
            return true;
        }

        return $this->renderAjax('upload', [
            'file' => $file,
            'model' => $model
        ]);
    }

    public function actionArchive($id)
    {
        $model = Task::findOne($id);
        $model->archive();
        return $this->redirect(['task/card', 'id' => $id]);
    }

    public function actionComplete($id)
    {
        $model = Task::findOne($id);
        $zip_name = $model->complete();
        if ($zip_name) {
            return $this->redirect(['task/card', 'id' => $id]);
            //return Yii::$app->response->SendFile($zip_name);
        }
        return $this->redirect(['task/card', 'id' => $id]);
    }

    public function actionStepComments($id_clone)
    {
        $model = ChainClonesSteps::findOne($id_clone);
        $model_comment = new StepClonesComment();
        if (Yii::$app->request->isAjax && $model_comment->load(Yii::$app->request->post())) {
            $model_comment->save();
            return true;
        }
        return $this->renderAjax('step-comments', [
            'model' => $model,
            'model_comment' => $model_comment
        ]);
    }

    public function actionDeleteFile($id, $id_task)
    {
        $file = Files::findOne($id);
        $file->delete();
        return $this->redirect(['task/card', 'id' => $id_task]);
    }

    public function actionDeleteExternal($id, $id_task)
    {
        $model = ExternalSource::findOne($id);
        $model->delete();
        return $this->redirect(['task/card', 'id' => $id_task]);
    }

    public function actionAddExternal($id_task, $id_step)
    {
       $model = new ExternalSource();

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            $model->id_step = $id_step;
            $model->id_task = $id_task;
            $model->save();
            return Json::encode(['message' => 'Внешний источник добавлен', 'id' => $model->id]);
        }

        return $this->renderAjax('add-external', [
            'model' => $model,
            'id_task'   => $id_task,
            'id_step'   => $id_step
        ]);
    }

    public function actionDelete($id)
    {
        $task = Task::findOne($id);
        $task->delete();
        return Json::encode(['task delete']);
    }

    public function actionAdd($id_project)
    {
        $task = new Task();
        $modelEdit = new TaskEdit();
        if (!empty(Yii::$app->request->post()) && $task->load(Yii::$app->request->post())) {
            $post = Yii::$app->request->post();
            $task->load(Yii::$app->request->post());
            $task = Task::createTask($task, $post, $modelEdit, $id_project);
            return  $this->redirect('/task/list?id_project=' . $task->id_project);
        }
        return $this->render('update', [
            'task' => $task,
            'modelEdit' => $modelEdit
        ]);
    }

    public function actionChange()
    {
        $tasks = Yii::$app->request->get('task');
        $data = Task::FilterByFirst($tasks);
        $model = new ChangeTask();
        $tasks = [];
        foreach ($data['tasks'] as $task){
            $tasks[] = Task::findOne($task['id']);
        }

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            $tasks = Yii::$app->request->post('Task');
            $model->doChange($tasks);
            return true;
        }

        return $this->renderAjax('change', [
            'data'  => $data,
            'model' => $model,
            'tasks' => $tasks
        ]);
    }

    public function actionStepsList($id_step)
    {
        $users = Steps::findOne($id_step)->group->getUsers()->asArray()->all();
        return $this->renderAjax('users-list', [
            'users' => $users
        ]);
    }

    public function actionCopy()
    {
        $tasks = Yii::$app->request->get('task');
        Task::copyTasks($tasks);
    }

    public function actionArchiveMass()
    {
        $tasks = Yii::$app->request->get('task');
        foreach($tasks as $task){
            $task_model = Task::findOne($task);
            $task_model->is_archive = 1;
            $task_model->status = Task::STATUS_ARCHIVE;
            $task_model->save(false);

        }
        return true;
    }

    public function actionAcceptMass()
    {
        $tasks = Yii::$app->request->get('task');
        Task::setStatusAccept($tasks);
    }

    public function actionDeleteMass()
    {
        $tasks = Yii::$app->request->get('task');
        if(empty($tasks)){
            return true;
        }
        Task::deleteAll([
            'AND',
            ['in', 'id', $tasks]
        ]);
    }

    public function actionUsersTasks($id_user, $status, $id_project = null)
    {
        if ($status != 'all') {
            $clone_steps = ChainClonesSteps::find()->where(['id_user' => $id_user])
                ->andWhere(['status' => $status])->all();
        } else{
            $clone_steps = ChainClonesSteps::find()->where(['id_user' => $id_user])
                ->all();
        }
        $tasks = [];
        foreach ($clone_steps as $clone_step) {
            $tasks[] = $clone_step->task->id;
        }

        $taskSearch = new TaskSearch();
        $dataProvider = $taskSearch->search(Yii::$app->request->get());
        $statuses = TasksHelper::getTaskStatusByUser($id_user, $tasks);
        $dataProvider->query->andFilterWhere(['in', Task::tableName() . '.id', $tasks]);
        if (!is_null($id_project)) {
            $dataProvider->query->andFilterWhere(['id_project' => $id_project]);
        }

        return $this->render('users-tasks', [
            'dataProvider' => $dataProvider,
            'taskSearch' => $taskSearch,
            'statuses' => $statuses
        ]);
    }

    public function actionUsersTasksDate($id_user, $status, $from, $to)
    {
        $clone_steps = ChainClonesSteps::find()->where(['id_user' => $id_user])
            ->all();
        $tasks = [];
        foreach($clone_steps as $clone_step){
            $tasks[] = $clone_step->task->id;
        }
        $taskSearch = new TaskSearch();
        $dataProvider = $taskSearch->search(\Yii::$app->request->get());
        $dataProvider->setPagination([
            'pageSize' => 10
        ]);
        $dataProvider->query->alias('t')->andFilterWhere(['in','id', $tasks]);
        $dataProvider->query->andWhere(['>','deadline', $from]);
        $dataProvider->query->andWhere(['<', 'deadline', $to]);
        return $this->render('users-tasks', [
            'dataProvider' => $dataProvider,
            'taskSearch'    => $taskSearch
        ]);
    }
}
